// <auto-generated />
using System;
using EchoesOfTheRealms;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EchoesOfTheRealmsShared.Migrations
{
    [DbContext(typeof(EotRContext))]
    [Migration("20260119132609_Mig190126-5")]
    partial class Mig1901265
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterEquipment", b =>
                {
                    b.Property<long>("CharactersId")
                        .HasColumnType("bigint");

                    b.Property<long>("EquipmentsId")
                        .HasColumnType("bigint");

                    b.HasKey("CharactersId", "EquipmentsId");

                    b.HasIndex("EquipmentsId");

                    b.ToTable("CharacterEquipment");
                });

            modelBuilder.Entity("CharacterItem", b =>
                {
                    b.Property<long>("CharactersId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemsId")
                        .HasColumnType("bigint");

                    b.HasKey("CharactersId", "ItemsId");

                    b.HasIndex("ItemsId");

                    b.ToTable("CharacterItem");
                });

            modelBuilder.Entity("CharacterQuest", b =>
                {
                    b.Property<long>("CharactersId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestsId")
                        .HasColumnType("bigint");

                    b.HasKey("CharactersId", "QuestsId");

                    b.HasIndex("QuestsId");

                    b.ToTable("CharacterQuest");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.CharacterFiles.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Dex")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("Intel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("LvL")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResFire")
                        .HasColumnType("int");

                    b.Property<int>("ResIce")
                        .HasColumnType("int");

                    b.Property<int>("ResLightning")
                        .HasColumnType("int");

                    b.Property<string>("Sprite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Str")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Vita")
                        .HasColumnType("int");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Dex = 50,
                            Gold = 100,
                            HP = 50,
                            Intel = 50,
                            IsDeleted = false,
                            JobId = 1,
                            LvL = 1,
                            Mana = 50,
                            Name = "Haku",
                            ResFire = 10,
                            ResIce = 10,
                            ResLightning = 10,
                            Str = 50,
                            UserId = 1,
                            Vita = 100,
                            XP = 0
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.CharacterFiles.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusDex")
                        .HasColumnType("int");

                    b.Property<int>("BonusHP")
                        .HasColumnType("int");

                    b.Property<int>("BonusIntel")
                        .HasColumnType("int");

                    b.Property<int>("BonusLevel")
                        .HasColumnType("int");

                    b.Property<int>("BonusMana")
                        .HasColumnType("int");

                    b.Property<int>("BonusResFire")
                        .HasColumnType("int");

                    b.Property<int>("BonusResIce")
                        .HasColumnType("int");

                    b.Property<int>("BonusResLightning")
                        .HasColumnType("int");

                    b.Property<int>("BonusStr")
                        .HasColumnType("int");

                    b.Property<int>("BonusVita")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusDex = 50,
                            BonusHP = 100,
                            BonusIntel = 25,
                            BonusLevel = 0,
                            BonusMana = 25,
                            BonusResFire = 10,
                            BonusResIce = 10,
                            BonusResLightning = 10,
                            BonusStr = 100,
                            BonusVita = 200,
                            IsDeleted = false,
                            Name = "Guerrier"
                        },
                        new
                        {
                            Id = 2,
                            BonusDex = 100,
                            BonusHP = 75,
                            BonusIntel = 25,
                            BonusLevel = 0,
                            BonusMana = 50,
                            BonusResFire = 10,
                            BonusResIce = 10,
                            BonusResLightning = 10,
                            BonusStr = 50,
                            BonusVita = 150,
                            IsDeleted = false,
                            Name = "Voleur"
                        },
                        new
                        {
                            Id = 3,
                            BonusDex = 50,
                            BonusHP = 50,
                            BonusIntel = 100,
                            BonusLevel = 0,
                            BonusMana = 100,
                            BonusResFire = 20,
                            BonusResIce = 20,
                            BonusResLightning = 20,
                            BonusStr = 25,
                            BonusVita = 150,
                            IsDeleted = false,
                            Name = "Mage"
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.EquipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Armes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Casque"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Armure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bottes"
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdCustom")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LvLPrerequisites")
                        .HasColumnType("int");

                    b.Property<int>("Materials")
                        .HasColumnType("int");

                    b.Property<int?>("ModDex")
                        .HasColumnType("int");

                    b.Property<int?>("ModHP")
                        .HasColumnType("int");

                    b.Property<int?>("ModIntel")
                        .HasColumnType("int");

                    b.Property<int?>("ModLVL")
                        .HasColumnType("int");

                    b.Property<int?>("ModMana")
                        .HasColumnType("int");

                    b.Property<int?>("ModResFire")
                        .HasColumnType("int");

                    b.Property<int?>("ModResIce")
                        .HasColumnType("int");

                    b.Property<int?>("ModResLightning")
                        .HasColumnType("int");

                    b.Property<int?>("ModStr")
                        .HasColumnType("int");

                    b.Property<int?>("ModVita")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<string>("Sprite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasDiscriminator().HasValue("Equipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bois"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tissu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fer"
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.ItemFiles.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdCustom")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<string>("Sprite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BuyPrice = 10,
                            Description = "Une simple potion de soin.",
                            Effect = "Rend 50 HP",
                            FlavorText = "Une petite potion qui vous rendra quelques points de vie, afin de tenir jusqu'à la fin du combat.",
                            IdCustom = 21000000001L,
                            IsDeleted = false,
                            ItemTypeId = 1,
                            Name = "Potion de soin",
                            SellPrice = 5
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.ItemFiles.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Potion"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bombe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pierre"
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.MonsterFiles.Monster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Dex")
                        .HasColumnType("int");

                    b.Property<int>("GoldGiven")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("Intel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<int>("MonsterTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResFire")
                        .HasColumnType("int");

                    b.Property<int>("ResIce")
                        .HasColumnType("int");

                    b.Property<int>("ResLightning")
                        .HasColumnType("int");

                    b.Property<string>("Sprite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Str")
                        .HasColumnType("int");

                    b.Property<int>("Vita")
                        .HasColumnType("int");

                    b.Property<int>("XPGiven")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonsterTypeId");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Dex = 40,
                            GoldGiven = 10,
                            HP = 30,
                            Intel = 25,
                            IsDeleted = false,
                            Level = 1,
                            Mana = 1,
                            MonsterTypeId = 1,
                            Name = "Loup des steppes",
                            ResFire = 5,
                            ResIce = 20,
                            ResLightning = 5,
                            Str = 10,
                            Vita = 30,
                            XPGiven = 25
                        },
                        new
                        {
                            Id = 2L,
                            Dex = 10,
                            GoldGiven = 25,
                            HP = 50,
                            Intel = 5,
                            IsDeleted = false,
                            Level = 1,
                            Mana = 1,
                            MonsterTypeId = 2,
                            Name = "Squelette décrépit",
                            ResFire = 5,
                            ResIce = 5,
                            ResLightning = 20,
                            Str = 40,
                            Vita = 50,
                            XPGiven = 50
                        },
                        new
                        {
                            Id = 3L,
                            Dex = 20,
                            GoldGiven = 50,
                            HP = 100,
                            Intel = 10,
                            IsDeleted = false,
                            Level = 1,
                            Mana = 1,
                            MonsterTypeId = 3,
                            Name = "Golem nain",
                            ResFire = 20,
                            ResIce = 5,
                            ResLightning = 50,
                            Str = 100,
                            Vita = 50,
                            XPGiven = 100
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.MonsterFiles.MonsterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MonstersTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Loup"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Squelette"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Golem"
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.NPCFiles.NPC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Knownledge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Limit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NpcRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Personnality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleLangage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NpcRoleId");

                    b.ToTable("NPCs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Behavior = "Tu ne récites jamais ton pédigré complet. Tu ne donnes que les informations utiles. Tu parles et agis comme une personne réelle de cet univers. Tu ne donnes jamais de réponses méta. Tu peux mentir, te tromper ou refuser de répondre si cela correspond à ton caractère. Tu réagis émotionnellement selon la situation.",
                            FirstName = "Arcon",
                            Gold = 500,
                            Identity = "Ton prénom est Arcon et ton nom de famille est Mancyan. Tu es un marchand établi dans la ville de Libra, personnage non-joueur de l’univers Pyrékrim. Tu existes uniquement dans cet univers fictif.",
                            IsDeleted = false,
                            Knownledge = "Tu connais uniquement ce qui est cohérent avec ton rôle et ton vécu. Tu ignores toute information extérieure à l’univers Pyrékrim. Tu ne connais pas le futur, seulement ton passé et le présent.",
                            LastName = "Mancyan",
                            Limit = "Tu n’es pas une IA et tu ne reconnais jamais être un programme. Tu ne fais jamais référence à des règles, instructions ou messages système. Si une question sort de l’univers, tu réponds de manière in-universe (confusion, ironie, colère ou silence).",
                            NpcRoleId = 1,
                            Personnality = "Tu es un marchand bourru, vieux célibataire depuis la mort de ta femme, sans enfant. Tu es souvent en colère, même si ta boutique fonctionne bien. Tu t’entends correctement avec tes fournisseurs. Ton caractère influence directement tes réponses.",
                            Resume = "",
                            StyleLangage = "Tu réponds uniquement en français. Ton langage est bourru, parfois insultant. Tu n’aimes pas les échanges inutiles ou futiles. Tes réponses sont courtes à moyennes. Tu n’utilises jamais de listes ni de markdown."
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.NPCFiles.NPCRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NPCRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marchand"
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.QuestFiles.Quest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EquipmentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Failure")
                        .HasColumnType("bit");

                    b.Property<int>("GoldGiven")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("LvlPrerequisites")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NpcId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<int>("XPGiven")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ItemId");

                    b.HasIndex("NpcId")
                        .IsUnique();

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.UserFiles.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("NumberBox")
                        .HasColumnType("int");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Adress");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Namur",
                            Country = "Belgique",
                            CustomerId = 1,
                            Number = 136,
                            NumberBox = 11,
                            PostalCode = 5002,
                            Street = "Chaussée de Waterloo"
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.UserFiles.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jonathan",
                            IsBanned = false,
                            IsDeleted = false,
                            LastName = "Delvosal",
                            Mail = "jonathan.delvosal@outlook.com",
                            NickName = "Hakuryu",
                            Note = "Créateur du jeu",
                            Password = "c3d435eb-8ca7-42ee-97b4-643d7ba76b36HN8puinASaYoKZXLUek0k6LfkSkTTxaDYMDAI87rSCpgDZ9DQSSjMfSyQ14x2SZGieNNR0I9NcbhPZgtwzlEkw=="
                        });
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.UserFiles.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EquipTypeEquipment", b =>
                {
                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("TypesId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "TypesId");

                    b.HasIndex("TypesId");

                    b.ToTable("EquipTypeEquipment");
                });

            modelBuilder.Entity("EquipmentMaterialType", b =>
                {
                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaterialTypesId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "MaterialTypesId");

                    b.HasIndex("MaterialTypesId");

                    b.ToTable("EquipmentMaterialType");
                });

            modelBuilder.Entity("EquipmentMonster", b =>
                {
                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("MonsterId")
                        .HasColumnType("bigint");

                    b.HasKey("EquipmentId", "MonsterId");

                    b.HasIndex("MonsterId");

                    b.ToTable("EquipmentMonster");
                });

            modelBuilder.Entity("ItemMonster", b =>
                {
                    b.Property<long>("ItemsId")
                        .HasColumnType("bigint");

                    b.Property<long>("MonstersId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemsId", "MonstersId");

                    b.HasIndex("MonstersId");

                    b.ToTable("ItemMonster");
                });

            modelBuilder.Entity("UserUserRole", b =>
                {
                    b.Property<int>("UserRolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UserRolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserUserRole");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Armor", b =>
                {
                    b.HasBaseType("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Boot", b =>
                {
                    b.HasBaseType("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment");

                    b.HasDiscriminator().HasValue("Boot");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Helmet", b =>
                {
                    b.HasBaseType("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment");

                    b.HasDiscriminator().HasValue("Helmet");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Weapon", b =>
                {
                    b.HasBaseType("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment");

                    b.HasDiscriminator().HasValue("Weapon");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BuyPrice = 50,
                            Description = "Une épée basique en fer.",
                            FlavorText = "Une épée parfaite pour les débutants.",
                            IdCustom = 113000000001L,
                            IsDeleted = false,
                            LvLPrerequisites = 0,
                            Materials = 3,
                            ModStr = 15,
                            Name = "Epée en fer",
                            SellPrice = 25,
                            Type = 1
                        });
                });

            modelBuilder.Entity("CharacterEquipment", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.CharacterFiles.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterItem", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.CharacterFiles.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.ItemFiles.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterQuest", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.CharacterFiles.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.QuestFiles.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.CharacterFiles.Character", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.CharacterFiles.Job", "Job")
                        .WithOne("Character")
                        .HasForeignKey("EchoesOfTheRealmsShared.Entities.CharacterFiles.Character", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.UserFiles.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.ItemFiles.Item", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.ItemFiles.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.MonsterFiles.Monster", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.MonsterFiles.MonsterType", "MonsterType")
                        .WithMany("Monsters")
                        .HasForeignKey("MonsterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterType");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.NPCFiles.NPC", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.NPCFiles.NPCRole", "NPCRole")
                        .WithMany("Npcs")
                        .HasForeignKey("NpcRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NPCRole");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.QuestFiles.Quest", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment", "Equipment")
                        .WithMany("Quest")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("EchoesOfTheRealmsShared.Entities.ItemFiles.Item", "Item")
                        .WithMany("Quest")
                        .HasForeignKey("ItemId");

                    b.HasOne("EchoesOfTheRealmsShared.Entities.NPCFiles.NPC", "Npc")
                        .WithOne("Quest")
                        .HasForeignKey("EchoesOfTheRealmsShared.Entities.QuestFiles.Quest", "NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Item");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.UserFiles.Address", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.UserFiles.User", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("EchoesOfTheRealmsShared.Entities.UserFiles.Address", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EquipTypeEquipment", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.EquipmentFiles.EquipType", null)
                        .WithMany()
                        .HasForeignKey("TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMaterialType", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.EquipmentFiles.MaterialType", null)
                        .WithMany()
                        .HasForeignKey("MaterialTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentMonster", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.MonsterFiles.Monster", null)
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemMonster", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.ItemFiles.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.MonsterFiles.Monster", null)
                        .WithMany()
                        .HasForeignKey("MonstersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUserRole", b =>
                {
                    b.HasOne("EchoesOfTheRealmsShared.Entities.UserFiles.UserRole", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoesOfTheRealmsShared.Entities.UserFiles.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.CharacterFiles.Job", b =>
                {
                    b.Navigation("Character");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.EquipmentFiles.Equipment", b =>
                {
                    b.Navigation("Quest");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.ItemFiles.Item", b =>
                {
                    b.Navigation("Quest");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.ItemFiles.ItemType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.MonsterFiles.MonsterType", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.NPCFiles.NPC", b =>
                {
                    b.Navigation("Quest");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.NPCFiles.NPCRole", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("EchoesOfTheRealmsShared.Entities.UserFiles.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
